---
exclude_paths:
  - External/**
  - DroneShow_Test/**
  - "**/*.config"

engines:
  cppcheck:
    enabled: true
    params:
      - name: suppress
        value: missingIncludeSystem

  trivy:
    enabled: false

languages:
  - Cpp