sonar.projectKey=munimaru62o_ECSDroneShow
sonar.organization=munimaru62o

sonar.sources=DroneShow_App/src, DroneShow_Game/src, ECSEngine/src
sonar.tests=DroneShow_Test
sonar.exclusions=External/**/*, script/**/*, .github/**/*

sonar.coverage.exclusions=\
  DroneShow_App/src/main.cpp, \
  DroneShow_Game/src/Game/Game.cpp, \
  DroneShow_Game/src/Game/Managers/InputManager.*, \
  ECSEngine/src/Engine/Render/**/*, \
  ECSEngine/src/Engine/Debug/**/*, \
  ECSEngine/src/Engine/Platform/**/*