flowchart TD

%% ===================================================
%% Logic Phase
%% ===================================================

subgraph LogicPhase["Logic Phase (Variable Tick)"]

%% Update
TD[TimelineDirectorSystem]

%% ApplyRequest
CFR[ColorFadeRequestSystem]
RSAR[RandomSwirlAxisRequestSystem]
RVR[RandomVelocityRequestSystem]
SAR[SpinAnimationRequestSystem]

TD --> CFR
TD --> RSAR
TD --> RVR
TD --> SAR

end


%% ===================================================
%% Physics Phase
%% ===================================================

subgraph PhysicsPhase["Physics Phase (Fixed Tick)"]

%% SpatialPartition
SP[SpatialPartitionSystem]

%% SpatialCache
SC[SpatialBoidCacheSystem]

%% ForceClear
FC[ForceClearSystem]

%% TargetGenerator
FSW[FormationSystemWireframe]
FSP[FormationSystemPointCloud]

%% TargetModifier
OR[OrbitSystem]

%% ForceGenerator
BO[BoidsSystem]
AT[AttractionSystem]
GV[GravitySystem]
LF[LiftSystem]
SW[SwirlSystem]
BD[BoundarySystem]
JM[JitterMovementSystem]
WD[WanderSystem]
DT[DartSystem]

%% Steering
ST[SteeringSystem]

%% VelocityGenerator
VI[VelocityIntegrationSystem]
VD[VelocityDirectionSystem]

%% VelocityDamping
DP[DampingSystem]

%% Constraint
SCN[SpeedConstraintSystem]
PCN[PlaneConstraintSystem]

%% TransformIntegration
TI[TransformIntegrationSystem]

%% PostTransform
DRV[DirectionRotationSystem Velocity]
DRF[DirectionRotationSystem Formation]
SA[SpinAnimationSystem]

%% MaterialModifier
CB[ColorBlinkSystem]
CF[ColorFadeSystem]


%% ---------------------------------------------------
%% Flow
%% ---------------------------------------------------

SP --> SC

SC --> FC

FC --> FSW
FC --> FSP

FSW --> OR
FSP --> OR

OR --> BO
OR --> AT
OR --> GV
OR --> LF
OR --> SW
OR --> BD
OR --> JM
OR --> WD
OR --> DT

BO --> ST
AT --> ST
GV --> ST
LF --> ST
SW --> ST
BD --> ST
JM --> ST
WD --> ST
DT --> ST

ST --> VI
VI --> VD

VD --> DP

DP --> SCN
SCN --> PCN

PCN --> TI

TI --> DRV
TI --> DRF
TI --> SA

DRV --> CB
DRF --> CB
SA --> CB
DRV --> CF
DRF --> CF
SA --> CF

end


%% ===================================================
%% Render Phase
%% ===================================================

subgraph RenderPhase["Render Phase (Variable Tick)"]

%% Request
MR[MaterialRequestSystem]

%% Lighting
SL[SceneLightingSystem]

%% Opaque
PMR[PrimitiveMeshRenderSystem]

end


%% ===================================================
%% Connections
%% ===================================================

%% Logic -> Physics
CFR --> SP
RSAR --> SP
RVR --> SP
SAR --> SP

%% Physics -> Render
CB --> MR
CF --> MR

MR --> SL
SL --> PMR
