// Copyright (c) 2026 munimaru62o. All rights reserved.

#pragma once

#include "Engine/Math/Matrix4.h"
#include "Engine/Math/Color.h"
#include "Engine/Math/Vector3.h"

#include <string>
#include <cassert>
#include <string_view>
#include <vector>

/**
 * @brief A unique identifier for a registered mesh resource within the RenderManager.
 */
using MeshID = size_t;
constexpr MeshID INVALID_MESH_ID = 0;

/**
 * @struct InstanceData
 * @brief Per-instance data sent to the GPU for hardware instancing.
 */
struct InstanceData
{
    Matrix4 worldMatrix = Matrix4::Identity();
    Color color = Color::White();
};

/**
 * @struct Vertex3D
 * @brief Standard per-vertex data containing position and normal vectors.
 */
struct Vertex3D
{
    Vector3 position = {};
    Vector3 normal = {};
};

/**
 * @enum PrimitiveMeshType
 * @brief Enumerates the built-in primitive 3D shapes supported by the engine.
 *
 * These primitives are procedurally generated by the PrimitiveMeshFactory
 * and are heavily optimized for batched rendering.
 */
enum class PrimitiveMeshType
{
    Cube,
    Sphere,
    Count
};
constexpr int NUM_MESH_TYPES = static_cast<int>(PrimitiveMeshType::Count);

/**
 * @struct MeshSourceData
 * @brief An intermediate container for raw mesh geometry before it is uploaded to the GPU.
 *
 * Holds the vertex and index buffers generated procedurally or loaded from disk.
 * This data is consumed by the RenderManager to create immutable hardware buffers.
 */
struct MeshSourceData
{
    std::vector<Vertex3D> vertices;
    std::vector<uint32_t> indices;
};

/**
 * @enum PixelShaderType
 * @brief Defines the available shading models for the rendering pipeline.
 */
enum class PixelShaderType
{
    Lit,
    UnLit,
    Hologram,
    Toon,
    Count
};
constexpr int NUM_SHADERS = static_cast<int>(PixelShaderType::Count);

/**
 * @brief Converts a string representation to its corresponding PrimitiveMeshType enum.
 * * @param str The string identifier (e.g., "Cube", "Sphere") typically parsed from JSON.
 * @return The corresponding PrimitiveMeshType. Defaults to Cube if the string is unrecognized.
 */
[[nodiscard]] inline PrimitiveMeshType ToPrimitiveMeshType(std::string_view str)
{
    if (str == "Cube")      return PrimitiveMeshType::Cube;
    if (str == "Sphere")    return PrimitiveMeshType::Sphere;

    assert(false && "Invalid primitive mesh type string");
    return  PrimitiveMeshType::Cube;
}

/**
 * @brief Converts a string representation to its corresponding PixelShaderType enum.
 * * @param str The string identifier (e.g., "Lit", "Hologram") typically parsed from configuration files.
 * @return The corresponding PixelShaderType. Defaults to Lit if the string is unrecognized.
 */
[[nodiscard]] inline PixelShaderType ToPixelShaderType(std::string_view str)
{
    if (str == "Lit")       return PixelShaderType::Lit;
    if (str == "UnLit")     return PixelShaderType::UnLit;
    if (str == "Hologram")  return PixelShaderType::Hologram;
    if (str == "Toon")      return PixelShaderType::Toon;

    assert(false && "Invalid shader type string");
    return  PixelShaderType::Lit;
}
